-- Migration: pivot_sessions table for tracking Practice Pivot game sessions
-- File: supabase/migrations/20260728_pivot_sessions.sql

CREATE TABLE IF NOT EXISTS pivot_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    original_thought TEXT NOT NULL,
    original_emotion_score SMALLINT NOT NULL CHECK (original_emotion_score >= 1 AND original_emotion_score <= 22),
    pivot_thought TEXT NOT NULL,
    new_emotion_score SMALLINT NOT NULL CHECK (new_emotion_score >= 1 AND new_emotion_score <= 22),
    zone_from TEXT NOT NULL CHECK (zone_from IN ('alignement', 'neutre', 'résistance')),
    zone_to TEXT NOT NULL CHECK (zone_to IN ('alignement', 'neutre', 'résistance')),
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE pivot_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own pivot sessions"
    ON pivot_sessions FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own pivot sessions"
    ON pivot_sessions FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE INDEX idx_pivot_sessions_user ON pivot_sessions(user_id, created_at DESC);
CREATE INDEX idx_pivot_sessions_scores ON pivot_sessions(original_emotion_score, new_emotion_score);

COMMENT ON TABLE pivot_sessions IS 'Tracks Practice Pivot game sessions: thought → pivot → new emotion level';
